# Generated by Django 3.1.1 on 2020-09-14 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_site_theme_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='our_pricing/img/default/default.png', upload_to='our_pricing/img/')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('topic_A', models.CharField(max_length=100)),
                ('topic_B', models.CharField(max_length=100)),
                ('disription', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='our_pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='our_pricing/img/default/default.png', upload_to='our_pricing/img/')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('offers', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
