# Generated by Django 3.1.1 on 2020-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_our_news_our_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_news',
            name='disription',
        ),
        migrations.AddField(
            model_name='our_news',
            name='description',
            field=models.CharField(default='des', max_length=100),
        ),
        migrations.AlterField(
            model_name='our_news',
            name='img',
            field=models.ImageField(blank=True, default='our_news/img/default/default.png', upload_to='our_news/img/'),
        ),
    ]
