# Generated by Django 3.1.1 on 2020-09-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_mid_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
