# Generated by Django 3.1.1 on 2020-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0012_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='mid_page_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='mid_page_B/img/default/default.png', upload_to='mid_page_B/img/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
