# Generated by Django 3.1.1 on 2020-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_img_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='slide_title',
            field=models.TextField(),
        ),
    ]
