# Generated by Django 3.1.1 on 2020-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0015_auto_20200917_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='work_process/img/default/default.png', upload_to='work_process/img/')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField(blank=True)),
            ],
        ),
    ]
