# Generated by Django 3.1.1 on 2020-09-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0016_work_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_process',
            old_name='des',
            new_name='description',
        ),
    ]
