# Generated by Django 3.1.1 on 2020-09-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0018_auto_20200922_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('b_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('options', models.TextField(blank=True)),
            ],
        ),
    ]
