import os
from pathlib import Path
BASE_DIR=Path(__file__).resolve().parent.parent
SECRET_KEY='v+9%l@@6upn5j(a#w^sp+$y4-am252o6_!d(8ab4l_!fn!)ah&'
DEBUG=True
ALLOWED_HOSTS=['127.0.0.1','ircement.herokuapp.com']
INSTALLED_APPS=[
	'control_panel.apps.ControlPanelConfig',
	'users.apps.UsersConfig',
	'main.apps.MainConfig',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
]
MIDDLEWARE=[
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF='web_01.urls'
TEMPLATES=[
	{
		'BACKEND':'django.template.backends.django.DjangoTemplates',
		'DIRS':[os.path.join(BASE_DIR,'templates')]
		,
		'APP_DIRS':True,
		'OPTIONS':{
			'context_processors':[
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]
WSGI_APPLICATION='web_01.wsgi.application'
DATABASES={
	'default':{
		'ENGINE':'django.db.backends.postgresql',
		'NAME':'d2av0e9vbm22ps',
		'HOST':'ec2-54-156-53-71.compute-1.amazonaws.com',
		'PORT':5432,
		'USER':'gshnkzvtnsmwoy',
		'PASSWORD'
		'':'1e99d42451b4f7259db2d3ba8b78fef4d5275b0732b00e359253d8118026e371'
		}
}
AUTH_PASSWORD_VALIDATORS=[
	{
		'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]
LANGUAGE_CODE='en-us'
TIME_ZONE='UTC'
USE_I18N=True
USE_L10N=True
USE_TZ=True
STATIC_URL='/static/'
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
# STATIC_ROOT=os.path.join(BASE_DIR,'static')
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),)